language: ruby
sudo: required
addons:
  chrome: stable
  postgresql: "9.6"
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
before_install:
- gem update --system
- gem install bundler
install:
- bundle install
- nvm install v10
- node -v
- npm i -g yarn
- yarn install
script:
- bundle exec rubocop
- export RAILS_ENV=test
- bundle exec rake db:create db:schema:load
- bundle exec rspec
after_success:
- if [ $TRAVIS_PULL_REQUEST == false ] && [ $TRAVIS_BRANCH == "master" ]; then
      openssl aes-256-cbc -K $encrypted_d7f80deb40b0_key -iv $encrypted_d7f80deb40b0_iv -in id_rsa.enc -out config/deploy_id_rsa -d;
      chmod 600 config/deploy_id_rsa;
      eval `ssh-agent -s`;
      ssh-add config/deploy_id_rsa;
      bundle exec cap staging deploy;
      ssh-agent -k;
  fi
env:
  global:
  - secure: x16+B4ioERzzKu2jYeRXwWDl2wys7ssNegalS3MJvIiit9WZvMAyBbIY2O0vSr4Ik86X7PQLAokTNFN4oOM3puZcs9Ix5lf2liQeN27dCDBi53tAbOF0rvfKB8A4nAv1Unrf/sw/AzW46c88u0/sKTqu+HWoyjfEUX79GJf7BB9F1/7z+RK06XhuPPjSRxgzZFniUfvoum/4wHvQt8zUusDDba8B3lIwPyDGL4euMJaNB56SHsszCmO4mu7+TExiM+oWbnyi+wFnqp0oBa6hyxwNIwAAeznig/Dshq2uPCuMXLaexAwVzaKhKlsPDsVw+xH0DUQ8/8RXzvIaJuhovQX72Jnj+/WrA9dLLBbm53JGUrD8BVjII5mZmzUshxWCpw/3XMocaDVwj8VMeAMcZpGdolXvC5nh3H/ABti0BibP3hDSXU5gNuxiS+HJsIC9jkwq7TGs8wxA8X4SULy1oM7v5qKT1z5dG7y9TwTiAJ1x0KHLdRgzXcm9iHqSwnNgfZ59pW/fvnhUMqo4E1wplTo5Oysr7qjw63LsklA8aKixDgWShHp0CsO3v2ragyZvyrL+sSast++c6+iQHVnp6Bt4IZs8zcLmEeWGGzWe5RZwdg0o9Wp+Ul2uIsPhSGzIVK5ahnjPqdHYLIDOL4A8emgFXAtNxZhaB8tIKTGHguo=
