default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("PG_HOST", 'localhost') %>
  database: diaper_dev
  username: <%= ENV.fetch("PG_USERNAME", 'postgres') %>
  password: <%= ENV.fetch("PG_PASSWORD", nil) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  timeout: 5000

staging:
  <<: *default
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  database: <%= ENV['POSTGRESQL_DATABASE'] %>
  host: <%= ENV['POSTGRESQL_ADDRESS'] %>

test:
  <<: *default
  database: diaper_test
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["DIAPER_DB_HOST"] %>
  pool: 5
  username: <%= ENV["DIAPER_DB_USERNAME"] %>
  password: <%= ENV["DIAPER_DB_PASSWORD"] %>
  database: <%= ENV["DIAPER_DB_DATABASE"] %>
  timeout: 5000
